### ISSUE TITLE
No need

### ISSUE THREAD

**Issue by BraveCaperCat2** [celsiusqc/create_dimensions_addon#1]
Just add the create mod to whatever modpack you want, stop making these "addon" mods for modpacks, addon mods are for adding onto mods.

**Comment by zachsai** [comment]
This addon mod adds custom items for my Modpack. You are incorrect. If you do not like the mod, do not download it. Simple as that

**Comment by BraveCaperCat2** [comment]
well mods shouldn't be named after a modpack, but they can be "originally designed for <insertmodpackhere>"

**Comment by zachsai** [comment]
That is a subjective belief. I can name it under my modpack to indicate it is intended to be used for my modpack.
